name: Build and Release Extension

on:
  push:
    branches:
      - master  # Change if needed (e.g., "master" or "dev")

jobs:
  release:
    name: Package and Release Extension
    runs-on: all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip Extension Files
        run: |
          mkdir -p dist
          zip -r dist/extension.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/extension.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Extension Release v1.0.${{ github.run_number }}"
          body: "🚀 New automatic release of the extension!"
          draft: false
          prerelease: false
